title: Ayse Bat # your name (or website title) here
logo: "/images/phot.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  First description 
  <br><br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/aysebat/">View My LinkedIn Profile</a> 
social:
    - icon: fa-twitter
      link: "#"
    - icon: fa-linkedin
      link: "#"
    - icon: fa-stack-exchange
      link: "#"
    - icon: fa-github
      link: "https://github.com/aysbtsco"
  
theme: jekyll-theme-minimal
google_analytics: UA-149860962-1 # your Google Analytics tracking ID here
